[2024-06-21T04:08:12.232+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-21T04:08:12.259+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gic_main_dag.extract manual__2024-06-21T04:07:42+00:00 [queued]>
[2024-06-21T04:08:12.270+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gic_main_dag.extract manual__2024-06-21T04:07:42+00:00 [queued]>
[2024-06-21T04:08:12.271+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-21T04:08:12.285+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract> on 2024-06-21 04:07:42+00:00
[2024-06-21T04:08:12.296+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2259) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-21T04:08:12.298+0000] {standard_task_runner.py:63} INFO - Started process 2261 to run task
[2024-06-21T04:08:12.298+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'gic_main_dag', 'extract', 'manual__2024-06-21T04:07:42+00:00', '--job-id', '228', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmplzm7s0t5']
[2024-06-21T04:08:12.299+0000] {standard_task_runner.py:91} INFO - Job 228: Subtask extract
[2024-06-21T04:08:12.347+0000] {task_command.py:426} INFO - Running <TaskInstance: gic_main_dag.extract manual__2024-06-21T04:07:42+00:00 [running]> on host 39e4faefdcb7
[2024-06-21T04:08:12.445+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gic_main_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-06-21T04:07:42+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-21T04:07:42+00:00'
[2024-06-21T04:08:12.447+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-21T04:08:12.453+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-21T04:08:12.454+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main_dag.py", line 100, in extract
    file_df = extract_csv_filenames()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main_dag.py", line 38, in extract_csv_filenames
    full_files = [ os.path.join(path_to_dir,filename) for filename in filenames if filename.endswith( suffix ) ]
                                                                                                      ^^^^^^
NameError: name 'suffix' is not defined
[2024-06-21T04:08:12.473+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=gic_main_dag, task_id=extract, run_id=manual__2024-06-21T04:07:42+00:00, execution_date=20240621T040742, start_date=20240621T040812, end_date=20240621T040812
[2024-06-21T04:08:12.493+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 228 for task extract (name 'suffix' is not defined; 2261)
[2024-06-21T04:08:12.513+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-21T04:08:12.536+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-21T04:08:12.539+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
