[2024-06-19T15:15:32.482+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T15:15:32.509+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: testing_dag.task_3 manual__2024-06-19T15:15:18.576888+00:00 [queued]>
[2024-06-19T15:15:32.520+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: testing_dag.task_3 manual__2024-06-19T15:15:18.576888+00:00 [queued]>
[2024-06-19T15:15:32.521+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-19T15:15:32.538+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): task_3> on 2024-06-19 15:15:18.576888+00:00
[2024-06-19T15:15:32.551+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1087) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-19T15:15:32.553+0000] {standard_task_runner.py:63} INFO - Started process 1089 to run task
[2024-06-19T15:15:32.555+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'testing_dag', 'task_3', 'manual__2024-06-19T15:15:18.576888+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp7i2adgtc']
[2024-06-19T15:15:32.556+0000] {standard_task_runner.py:91} INFO - Job 48: Subtask task_3
[2024-06-19T15:15:32.616+0000] {task_command.py:426} INFO - Running <TaskInstance: testing_dag.task_3 manual__2024-06-19T15:15:18.576888+00:00 [running]> on host 80ed35ae19d6
[2024-06-19T15:15:32.681+0000] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'task_3', field 'sql'. Template: '/opt/***/data/scripts/master-reference-sql.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/data/scripts/master-reference-sql.sql
[2024-06-19T15:15:32.685+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2633, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1337, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/data/scripts/master-reference-sql.sql
[2024-06-19T15:15:32.696+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=testing_dag, task_id=task_3, run_id=manual__2024-06-19T15:15:18.576888+00:00, execution_date=20240619T151518, start_date=20240619T151532, end_date=20240619T151532
[2024-06-19T15:15:32.711+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 48 for task task_3 (/opt/airflow/data/scripts/master-reference-sql.sql; 1089)
[2024-06-19T15:15:32.729+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T15:15:32.747+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T15:15:32.749+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
